#!/usr/bin/env bash

LOCAL_IPYTHON="ipython-qtconsole --gui-completion"
REMOTE_IPYTHON="ipython kernel --pylab=inline"
REMOTE_PIDFILE=/tmp/`whoami`.$$.ipypid

E_BADARGS=65

if [ $# -eq 0 ]
then
    echo "Doing local. If you want to run over ssh, supply a host."
    ipython-qtconsole
    exit
elif [ $# -ne 1 ]
then
  echo "Usage: `basename $0` {remote host}"
  echo "Remote host can optionally include user and port: user@host:port"
  echo "With no arguments ipython-qtconsole runs on localhost"
  exit $E_BADARGS
fi

IPYJSON=`mktemp`

ssh $1 "($REMOTE_IPYTHON 2>&1 &) | head -n 2 | tail -n 1 | awk '{print \$3}' | tee $REMOTE_PIDFILE | xargs -i cat ~/.ipython/profile_default/security/{} | head -n 8" > $IPYJSON

$LOCAL_IPYTHON --ssh $1 --existing $IPYJSON

ssh $1 "kill \`cat $REMOTE_PIDFILE | tr -cd [:digit:]\` && rm $REMOTE_PIDFILE"
rm $IPYJSON